version: '3.3'
services:
  variant-loader:
    image: dbmi/pic-sure-hpds-etl:master_62b8ef6
    environment:
      - HEAPSIZE=26000
      - LOADER_NAME=VCFLocalLoader
    volumes:
      - ./hpds:/opt/local/hpds
      - ./vcfLoad:/opt/local/hpds/vcfInput
      - ./hpds/all:/opt/local/hpds/vcfOutput
