version: '3.3'
services:
  variantmetadata-loader:
    image: dbmi/pic-sure-hpds-etl:als-sprint-2_2f519a3
    environment:
      - HEAPSIZE=4096
      - LOADER_NAME=VariantMetadataLoader
    volumes:
      - ./hpds:/opt/local/phenocube
      - ./hpds:/opt/local/hpds
