SMALL_JOB_LIMIT = 100
SMALL_TASK_THREADS = 1
LARGE_TASK_THREADS = 1

# Logging File Output https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.file-output
# If you are adding additional log files please add them to /var/log/ directory.
logging.file.name=/var/log/open-hpds.log